version: "3.7"

services:
  redis:
    image: redis:5.0.5
    ports:
      - "6379:6379"

  proxy:
    build: "."
    ports:
      - "8888:8888"
    entrypoint:
      - ./server
      - -p
      - "8888"
      - --redis-addr
      - "redis:6379"
    links:
      - redis
